ARG CADDY_VERSION=2.11.6

FROM caddy:${CADDY_VERSION}-builder-alpine AS builder

ARG DNS_PLUGIN

RUN test -n "$DNS_PLUGIN" && \
    xcaddy build --with "$DNS_PLUGIN"

FROM caddy:${CADDY_VERSION}-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
